chicago = City.create!(name: "Chicago")

gabi = User.create!(name: "Gabi", email: "gabi@dbc.com", password: "1234")
andrew = User.create!(name: "Andrew", email: "andrew@dbc.com", password: "1234")

italian = Restaurant.create!(name: "Mama Mia!!", city_id: chicago.id)
french = Restaurant.create!(name: "Mon Mere", city_id: chicago.id)
mexican = Restaurant.create!(name: "Mi Madre", city_id: chicago.id)
korean = Restaurant.create!(name: "Ileol Suga", city_id: chicago.id)
swedish = Restaurant.create!(name: "Milde", city_id: chicago.id)

Review.create!(user_id: gabi.id, restaurant_id: italian.id, title: "Best f00D eva!", content: "Food was great!", rating: 5)
Review.create!(user_id: gabi.id, restaurant_id: french.id, title: "Pretty good", content: "Food was great!", rating: 4)
Review.create!(user_id: gabi.id, restaurant_id: korean.id, title: "Horrible", content: "Food was great!", rating: 1)
Review.create!(user_id: gabi.id, restaurant_id: mexican.id, title: "Awesome", content: "Food was great!", rating: 4)
Review.create!(user_id: gabi.id, restaurant_id: swedish.id, title: "Most terrible", content: "Food was great!", rating: 2)
Review.create!(user_id: gabi.id, restaurant_id: italian.id, title: "Best f00D eva! FOR REALZ", content: "Even better than the last time I went", rating: 5)
Review.create!(user_id: andrew.id, restaurant_id: italian.id, title: "Awesomesauce", content: "Food was great!", rating: 5)
Review.create!(user_id: andrew.id, restaurant_id: mexican.id, title: "Greatest f00D eva!", content: "Food was great!", rating: 5)
Review.create!(user_id: andrew.id, restaurant_id: swedish.id, title: "Deliciousness", content: "Food was great!", rating: 4)
Review.create!(user_id: andrew.id, restaurant_id: french.id, title: "Deliciousness squared", content: "Food was great!", rating: 5)
Review.create!(user_id: andrew.id, restaurant_id: french.id, title: "Great food", content: "Food was great!", rating: 5)
Review.create!(user_id: andrew.id, restaurant_id: swedish.id, title: "Awesomeness!", content: "Great service", rating: 5)
